### ISSUE TITLE
Removing a SA-Processing

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdverse/rjdemetra#144]
Is it possible to add a new function to remove a SA-Processing from a WS ?

**Comment by AQLT** [comment]
I think this function should be in `rjdworkspace` (which already contains functions to remove SaItems) and not in `RJDemetra`. I think a new function should be added in Java (here https://github.com/nbbrd/jdemetra-sa-advanced/blob/develop/jdr/src/main/java/ec/tstoolkit/jdr/ws/Workspace.java, ), if you were referring to the Java implementation I think the issue should in the Java repository?

**Comment by TanguyBarthelemy** [comment]
Ok I'll transfer this issue to **rjdworkspace** (as future development) and raise a new issue in the java repo asking to create a new java routine for R package with the removing functionnality.

**Comment by AQLT** [comment]
It should be easy to add this new function, I think something like this should work
```
public void removeMultiProcessing(int idx) {
    multiProcessing.remove(idx);
}
```
But I don't have time to test it in the short term.

**Comment by TanguyBarthelemy** [comment]
Ok thanks!
