### ISSUE TITLE
Variables unavailable from `user_defined_variables()`

### ISSUE THREAD

**Issue by TanguyBarthelemy** [rjdverse/rjdemetra#151]
Some variables from `user_defined_variables()` are missing in the output:

``` r
library("RJDemetra")

"decomposition.a1b" %in% user_defined_variables()
#> [1] TRUE
mod_x13 <- x13(AirPassengers, spec = "RSA5c", userdefined = "decomposition.a1b")
mod_x13$user_defined$decomposition.a1b
#> NULL
```

<sup>Created on 2024-10-04 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

This also applies to the variables:

- `decomposition.a1b`
- `decomposition.b12`
- `decomposition.b14`
- `decomposition.b15`
- `decomposition.b16`
- `decomposition.b18`
- `decomposition.b19`
- `decomposition.c3`
- `decomposition.c8`
- `decomposition.c12`
- `decomposition.c14`
- `decomposition.c15`
- `decomposition.c16`
- `decomposition.c18`
- `decomposition.c19`
- `decomposition.d3`
- `decomposition.d10b`
- `decomposition.d14`
- `decomposition.d15`
- `decomposition.d16b`
- `decomposition.d19`
- `decomposition.d20`

I don't know if there is a context (a specification / a series) for which these variables are non-zero?

Also I can't find any documentation for these variables.

**Comment by AQLT** [comment]
The variable with a "b" are linked to the backast:
``` r
library("RJDemetra")
mod_x13 <- x13(AirPassengers, spec =  x13_spec(x11.bcasts = -1), userdefined = c("decomposition.a1b", "decomposition.d10b", "decomposition.d16b"))
c(mod_x13$user_defined)
#> $decomposition.a1b
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1948  99.31140 109.22563 119.89732 111.41287 109.11529 122.25534 135.43102
#>            Aug       Sep       Oct       Nov       Dec
#> 1948 137.69953 124.24158 110.39259  94.96186 109.48544
#> 
#> $decomposition.d10b
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1948 0.9005604 0.9549446 1.0704320 1.0013108 0.9496772 1.0733051 1.1659194
#>            Aug       Sep       Oct       Nov       Dec
#> 1948 1.1848806 1.0682456 0.9156335 0.8078757 0.9077981
#> 
#> $decomposition.d16b
#>            Jan       Feb       Mar       Apr       May       Jun       Jul
#> 1948 0.9026796 0.9881503 1.0735216 0.9875029 0.9587198 1.0638988 1.1686630
#>            Aug       Sep       Oct       Nov       Dec
#> 1948 1.1834300 1.0613507 0.9301032 0.8004740 0.9061660
```

For the other variables, the dictionnary is coherent with JDemetra+ where you can also export them (even if they might not exist), so I think the question should be asked in other repositories

**Comment by TanguyBarthelemy** [comment]
Thank you Alain for your quick answer!
