### ISSUE TITLE
Problem with fixed coefficients for usrdef.variables

### ISSUE THREAD

**Issue by AlessandroPiovani** [rjdverse/rjdemetra#157]
When I use get_model() on a workspace that contains series with fixed coefficients for usrdef.var, I obtain the following warning/error

Warning messages:
Error in ts_variable$getTsData(): attempt to apply non-function
Error while importing a model: NULL object will be returned

The get_model() function processes and returns all the other time series without fixed coefficients in usrdef.var, but it returns NULL for the series with fixed coefficients in usrdef.var.

I have uploaded an example of code in which this problem happen: run the test-fixed-coefficients.R script to see the problem
[test_fixed_coefficients.zip](https://github.com/user-attachments/files/17939927/test_fixed_coefficients.zip)

**Comment by AQLT** [comment]
Thanks, it is fixed in #158.
